kaping_host: <%= ENV['KAPING_HOST'] || 'test_host' %>
kaping_index: <%= ENV['KAPING_INDEX'] || 'test_index'  %>
kaping_result_size: <%= ENV['KAPING_RESULT_SIZE'] || '100'  %>
kaping_log_level: <%= ENV['KAPING_LOG_LEVEL'] || :debug %>