kaping_host: <%= ENV['KAPING_HOST'] || 'nil' %>
kaping_index: <%= ENV['KAPING_INDEX'] || 'nil'  %>
kaping_result_size: <%= ENV['KAPING_RESULT_SIZE'] || '50'  %>
kaping_log_level: <%= ENV['KAPING_LOG_LEVEL'] || :debug %>
